easy_admin:
    site_name: word_training_site_name
    design:
        form_theme:
             - 'horizontal'
             - '@CustomEasyAdminBundle/Resources/views/form/form_theme.html.twig'
        templates:
            layout: '@CustomEasyAdminBundle/Resources/views/default/custom_layout.html.twig'

        menu:
            - url: '/'
              label: menu.go-public
              icon: home
            - entity: User
              label: menu.users
              icon: user
            - entity: Dictionary
              default: true
              label: menu.dictionaries
              icon: cube
            - entity: Word
              label: menu.words
              icon: cube
            - route: admin_settings
              label: menu.settings
              icon: cogs
    entities:
        User:
            class: AppBundle\Entity\User
            list:
                title: Users
                fields:
                    - username
                    - roles
                    - enabled
                    - lastLogin
                actions: [ search, show, new, edit, delete ]
            form:
                fields:
                    - username
                    - property: email
                      type: email
                      type_options: { required: false }
                    - enabled
                    - property: plainPassword
                      label: password
                      type: password
                      type_options: { required: true}
                    - roles
            edit:
                fields:
                    - property: plainPassword
                      label: new password
                      type: password
                      type_options: {required: false}

        Dictionary:
            controller: Custom\EasyAdmin\Controller\DictionaryAdminController
            class: AppBundle\Entity\Dictionary

            list:
                title: Dictionaries
                fields:
                    - id
                    - name
                    - words
                    - property: processingInfo
                      template: '@CustomEasyAdminBundle/Resources/views/dictionary/field_dictionary_processing.html.twig'
                      sortable: false
                actions: [ search, show, new, edit, delete ]
            show:
                fields: [ 'id', 'name', 'words' ]
            form:
                fields:
                    - name
                    - property: words
                      type: Custom\EasyAdmin\Form\WordsCollectionType
            new:
                form_options:
                    csrf_protection: false
        Word:
            class: AppBundle\Entity\Word
            disabled_actions: [ new, edit ]
            list:
                title: Words
                actions: [ 'show', '-new', '-edit', 'delete' ]
                fields:
                    - id
                    - property: spelling
                      type: text
                    - property: transcription
                      template: '@CustomEasyAdminBundle/Resources/views/word/field_word_transcription.html.twig'
                    - property: pronounce
                      template: '@CustomEasyAdminBundle/Resources/views/word/field_word_pronounce.html.twig'
                      sortable: false
                    - property: translation
                      template: '@CustomEasyAdminBundle/Resources/views/word/field_word_cut_translation.html.twig'
                    - property: dictionary
            show:
                fields:
                   - id
                   - spelling
                   - property: transcription
                     template: '@CustomEasyAdminBundle/Resources/views/word/field_word_transcription.html.twig'
                   - property: pronounce
                     template: '@CustomEasyAdminBundle/Resources/views/word/field_word_pronounce.html.twig'
                   - property: translation
                     type: text
                   - dictionary